python/python_9_project/rooms/rooms/urls.py
from django.contrib import admin
from django.urls import path, include

from room import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('room/', include('room.url', namespace='room'))
]

python/python_9_project/rooms/room/models.py
from django.db import models
from .validators import validate_duration


class Room(models.Model):
    number = models.PositiveIntegerField(verbose_name='номер', unique=True)
    name = models.CharField(max_length=50, verbose_name='название')
    capacity = models.PositiveIntegerField(verbose_name='вместимость')
    has_projector = models.BooleanField(verbose_name='наличие проектора')

    class Meta:
        verbose_name = 'Переговорка'
        verbose_name_plural = 'Переговорки'

    def __str__(self):
        return '{}, {}'.format(
            self.number,
            self.name)


class Reserve(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name='переговорка')
    reserve_date = models.DateField(verbose_name='дата начала')
    reserve_time = models.TimeField(verbose_name='время начала')
    duration = models.PositiveSmallIntegerField(verbose_name='продолжительность', validators=[validate_duration])
    name = models.CharField(max_length=100, verbose_name='имя')

    class Meta:
        verbose_name = 'Резерв переговорки'
        verbose_name_plural = 'Резервы переговорок'

    def __str__(self):
        return '{}, {}, {}, {}'.format(
            self.room,
            self.reserve_date,
            self.reserve_time,
            self.name)

python/python_9_project/rooms/room/forms.py
from datetime import timedelta
from django import forms
from .models import Reserve


class ReserveForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.__room = kwargs.pop('room')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Reserve
        fields = ('reserve_date', 'reserve_time', 'duration', 'name',)
        widgets = {
            'reserve_date': forms.SelectDateWidget()
        }

    def clean(self):
        reserve_date = self.cleaned_data['reserve_date']
        reserve_time = self.cleaned_data['reserve_time']
        duration = self.cleaned_data['duration']

        _our_start = reserve_time.hour
        _our_end = reserve_time.hour + duration

        all_reserves = Reserve.objects.filter(room=self.__room, reserve_date=reserve_date)
        for reserve in all_reserves:
            _start = reserve.reserve_time.hour
            _end = reserve.reserve_time.hour + reserve.duration
            if not (_our_start > _end or _our_end < _start):
                self.add_error('reserve_time', 'Кто-то успел до тебя')

    def clean_name(self):
        name = self.cleaned_data['name']
        if name == 'Коля':
            self.add_error('name', 'Извини, приятель, тебе нельзя забронировать')
        return name

python/python_9_project/rooms/room/views.py
from datetime import datetime, date, time
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import reverse
from .models import Room
from .forms import ReserveForm


def index(request):
    template = loader.get_template('home.html')
    rooms = Room.objects.all()
    context = {
        'rooms': rooms
    }
    return HttpResponse(template.render(context, request))


def reserve(request, room_id):
    try:
        room = Room.objects.get(id=room_id)
    except Room.DoesNotExist:
        raise Http404('Room not found')

    if request.POST:
        form = ReserveForm(request.POST, room=room)
        if form.is_valid():
            _reserve = form.save(commit=False)
            _reserve.room = room
            _reserve.save()
            return HttpResponseRedirect(reverse('index', args=()))
    else:
        _time = time(datetime.now().time().hour + 1, 0)
        form = ReserveForm(initial={
            'room': room,
            'reserve_date': date.today(),
            'reserve_time': _time,
            'duration': 2
        }, room=room)

    template = loader.get_template('reserve.html')
    context = {
        'room': room,
        'form': form
    }
    return HttpResponse(template.render(context, request))

python/python_9_project/rooms/room/templates/base.html
<html>
  <head>
    <style>
      * {
        font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
      }
      h1, .table td, .table th {
        padding: 10px 20px;
      }
    </style>
  </head>
</html>
<body>
  {% block content %}{% endblock %}
</body>

python/python_9_project/rooms/room/templates/home.html
{% extends 'base.html' %}

{% block content %}

  <h1>Переговорки</h1>

  {% if rooms %}

      {% for room in rooms %}

        <h2>{{ room.number }}, {{ room.name }}</h2>

        <a href="{% url 'room:reserve' room.id %}">Забронировать</a>

        {% with room.reserve_set.all as reserves %}

          <table>
            {% for reserve in reserves %}
              <tr>
                <td>{{ reserve.reserve_date }}</td>
                <td>{{ reserve.reserve_time }}</td>
                <td>{{ reserve.duration }}</td>
                <td>{{ reserve.name }}</td>
              </tr>
            {% endfor %}
          </table>

        {% endwith %}

      {% endfor %}

  {% else %}
    <p>Переговорные комнаты не добавлены.</p>
  {% endif %}

{% endblock %}

python/python_9_project/rooms/room/templates/reserve.html
{% extends 'base.html' %}

{% block content %}

  <h1>Забронировать {{ room.number }}</h1>

  <form method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Забронировать">

  </form>

{% endblock %}